### ISSUE TITLE
"minimum max" filter bug

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#107]
@jbloom currently if I [adjust](https://dms-vep.org/SARS-CoV-2_XBB.1.5_RBD_DMS_mAB-52/htmls/mAb_52_mut_effect.html) "minimum max of escape at site' it does not filter out sites that are in the library but have been removed by other filters (dark grey squares, see attached). I believe this is a bug as it previously was filtering just for the minimum max sites and removing everything else. line plot seems to work as expected.

<img width="1315" alt="image" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/22810662/7322d165-b20a-4c07-8314-0b18e483ab8e">

**Comment by Bernadetadad** [comment]
@jbloom could you fix this when you have time, it's hard to look at mAb escape heat maps with this bug in place

**Comment by jbloom** [comment]
If you need a short-term workaround for a paper figure, let me know.

**Comment by jbloom** [comment]
This is only a problem with the antibody escape plots, not the ones with functional effects. Maybe the issue is in `polyclonal`?
