### ISSUE TITLE
allow non-alphanumeric characters in summary keys

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#112]
@jbloom would it be possible to allow non-alphanumeric characters in keys of summary file. Specifically I would like to call functional selections something like `Entry in 2,3-linked sialic acid cells` as opposed to below but I get error if I do so. 
```
    Entry in 23 linked sialic acid cells:  # name of functional selection
      condition: 293_SA23_entry  # condition specified in `avg_func_effects`
      effect_type: func_effects  # "func_effects" or "latent_effects"
      positive_color: "#009E73"  # green
      negative_color: "#F0E442"  # yellow
      max_at_least: 1
      min_at_least: 0
      init_min_value: -3  # initial min value in slider
```

**Comment by jbloom** [comment]
I'm not sure if this is the greatest idea as it could lead to some funny file names, so at least consider just manually editing the strings plots for paper figures at the end.

But if you want to try, see if it works to put in quotes, such as:
```
"Entry in 2,3-linked sialic acid cells":
  <some_other_stuff>
```

I'm not sure if this will work, but I think it might. Report back here if it works!
