### ISSUE TITLE
remove titles / legends from interactive figures in place of VitePress configuration

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline-3#121]
Right now the configuration for plots made by `Altair` allow the option to specify a title and legend in the YAML configuration. However, people do not seem to be using that much.

In addition, with the new ability to make nicely formatted VitePress pages (see [here](https://github.com/dms-vep/dms-vep-pipeline-3/tree/main/homepage)), it might be easier just to remove the legends / titles from default `Altair` plots rendered by pipeline as plots are mostly self-explanatory, and then use VitePress functionality to make much more detailed and better legends for key reader-facing plots.

If anyone has any input on this (@caelanradford @Bernadetadad @bblarsen-sci @Caleb-Carr or others), please reply to this issue with your thoughts ASAP. If you are not even using the legends / titles in the configuration YAML and have basically just been copying the defaults from other examples, then that is probably a good indication that this change is a good one.

**Comment by Caleb-Carr** [comment]
I think this change makes sense because I have been basically copying the defaults and don't really use the legend functionality

**Comment by bblarsen-sci** [comment]
I didn't even know there was a legend functionality!
