### ISSUE TITLE
VitePress deployment failure

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline-3#127]
See [this failure](https://github.com/dms-vep/dms-vep-pipeline-3/actions/runs/8992566553).

Not sure if it is stochastic or is because a GitHub action needs to be updated?

@WillHannon-MCB, do you know?

**Comment by bblarsen-sci** [comment]
Try changing node-version: from `[18.x]` in the `.github/workflows/deploy.yaml` to `[20.x]`

**Comment by WillHannon-MCB** [comment]
Like @bblarsen-sci said, it seems like a version issue. If that doesn't fix it, let me know and I'll fix it tomorrow!

**Comment by jbloom** [comment]
@WillHannon-MCB, is there any reason not to update this to the latest versions rather than actions `@v3` and `node-verison: [20.x]`?

The latest versions would be `node-version: [22.x]`, ` actions/checkout@v4`, `actions/setup-node@v4`, and `peaceiris/actions-gh-pages@v4`.

**Comment by WillHannon-MCB** [comment]
I made a pull request with the updated version of Node. I ensured that the website was built correctly using Node `20.X`. Unfortunately, merging the pull request is the easiest way to check if the action works.
