### ISSUE TITLE
what is relationship between `.vitepress/config.mjs` and `index.md` metadata for VitePress?

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline-3#129]
@WillHannon-MCB, there is some highly similar information specified in the `.vitepress/config.mjs` file and the `index.md` in `./homepage/`. I don't quite understand what is the difference between them: are both needed, and if so which are used where?

**Comment by WillHannon-MCB** [comment]
Both are needed. Although they look similar, they're doing different things. The `index.md` file populates the Homepage (`index.html`), whereas the `config.mjs` configures the entire site. Currently, it's populating fields in each page's `<head>` tag, configuring the Navigation bar, and adding a footer to each page.

There are other [*optional* ways ](https://vitepress.dev/guide/getting-started#the-config-file) to use the `config.mjs` file to customize the size.
