### ISSUE TITLE
Stochastic duplication of `Altair` plots on VitePress homepage

### ISSUE THREAD

**Issue by WillHannon-MCB** [dms-vep/dms-vep-pipeline-3#132]
There is a strange phenomenon where certain `Altair` plots are duplicated on the VitePress site. Only one of the two plot 'containers' renders properly when this occurs.

There are no issues with the `markdown` or compiled `HTML` files. It seems to be an issue with 'Hydration' – the process whereby `Vue` (the Javascript library behind VitePress) adds reactivity to the static `HTML` document. My current guess is that the issue stems from the asynchronous way data is loaded into the `Altair` Vue component.

**Comment by Caleb-Carr** [comment]
For the lassa build (https://dms-vep.org/LASV_Josiah_GP_DMS/), I am still seeing stochastic duplication of charts and markdown text randomly not appearing (see images below).
<img width="1069" alt="Screenshot 2024-05-13 at 5 43 24 PM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/43453129/8f1fe600-eeba-4062-aa02-a5d75ea3b69c">
<img width="1104" alt="Screenshot 2024-05-13 at 5 43 12 PM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/43453129/508c50c9-4b85-409d-a5fa-cbb66dbf1483">
<img width="1109" alt="Screenshot 2024-05-13 at 5 43 01 PM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/43453129/083cda03-92e8-4e03-9fe6-bd26bfd25fd5">

**Comment by WillHannon-MCB** [comment]
I noticed the duplication issue yesterday during VEP subgroup. I'll do some more investigation today.

The missing text is mysterious. Is this happening on the same page as an `Altair` plot?

**Comment by Caleb-Carr** [comment]
The missing text is also on a page with `Altair` plots but it seems if you leave the page and come back to it, it appears correctly
