### ISSUE TITLE
Replicate correlation scatterplots plots

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#137]
@jbloom could we make replicate correlation scatterplots to be made by the pipeline? We have those colored squares but they don't really show all the data and I'd rather looks at a scatterplots. I feel like these plots came up in all 3 DMS paper I wrote and each time I just made them manually, so it would be nice to have them integrated in the pipeline. I'll make these myself for H5 paper but would be good to have these generated by the pipeline automatically at some point.

**Comment by jbloom** [comment]
Sure, I'm happy to do that. I will work on adding it.
