### ISSUE TITLE
Is there a better way to display the polyclonal fitting based on different concentrations?

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#146]
Not a bug, just commenting on an idea for a new feature for the polyclonal fitting for antibodies/serum with multiple different concentrations. 

We often want to know how inclusion of different concentrations impacts the data. Right now, it is only possible to do this manually in the `antibody_escape_config.yml`. Is it possible to have polyclonal run on the different combinations of concentrations so there is some sort of dropdown or checkbox to select different concentrations that show up in the analysis page? 

Rather than having it run on all samples automatically, maybe it could be a flag we set somewhere in the `antibody_escape_config.yml`, like include something like this:

**run_combinations_of_concentrations: true**

That way, the more computationally expensive fitting of all combinations of concentrations is only done on selections we are curious about. 

Then, if we are looking at the data, we can more immediately see how including or excluding different concentrations impacts the data. This came up because @jbloom and I were looking at the data outputs for some selections, and wondering how including different concentrations impacts the data, and it's currently not possible to do this without rerunning the pipeline.

There would need to be some dropdown on the analysis page where the different concentrations individually or combined can be toggled to see how it impacts the data (see screenshot below).

<img width="823" alt="Screenshot 2024-07-22 at 1 05 53 PM" src="https://github.com/user-attachments/assets/2bb6f4fb-7c0c-4545-8901-d423d8f96b69">

If this is not necessary or useful of an idea, feel free to disregard and delete.

**Comment by jbloom** [comment]
I think this is a good idea in principle. But might take some effort to implement:
- there are many combinations once the number of concentrations gets >= 3, so it would be a lot to fit them all so would which ones to fit just be specified?
- we would also somewhere have to specify which ones to carry forward for averages.

So for this reason, just doing manually setting these as currently could still be easier in many cases. You could add to `antibody_selections` additional keys like `serum_fit_conc_X_and_Y` to have different notebooks in docs with fits to same experiment w different concentration choices.
