### ISSUE TITLE
Include inverse Simpson index analysis in 'analyze_variant_counts'

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#15]
It appears this analysis/altair figure was removed in v3.0. If others didn't find this useful, feel free to ignore, but I personally found it handy to be included in the pipeline analysis just to get a quick idea of diversity that is present.

**Comment by jbloom** [comment]
This calculation is done in cell [11] of this notebook:
https://dms-vep.github.io/dms-vep-pipeline/analyze_variant_counts.html
