### ISSUE TITLE
defaults in environment yaml

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/dms-vep-pipeline-3#151]
After updating to `miniforge`, creating the `dms-vep-pipeline-3` conda environment from the yaml results in the following error: 

```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>
```

I am assuming this is because `defaults` is still listed in the `evironment.yml` and because miniforge pulls only from the `conda-forge` channel, can we remove the channels section or is the `bioconda` channel still unrestricted?

**Comment by jbloom** [comment]
We should **not** remove the `channels` section, but does it fix things if you just remove `defaults` as one of the channels? Try that and see if it works; if it does make a pull request. If it doesn't fix things, let me know and I will look into it more.

**Comment by Caleb-Carr** [comment]
Removing `defaults` seemed to fix the issue but I do not have permission for pushing the branch with the fix for a pull request.

**Comment by jbloom** [comment]
Try the pull request now.

Can you also increment the version (can be minor version number) and describe the change in the CHANGELOG?
