### ISSUE TITLE
download altair line plots separately

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#155]
Is it possible to do something so that line plots from summary could be downloaded separately from heat maps? My personal mac can just about handle it but one at work cannot deal with so many vectors coming from these ridiculous size heatmaps and lineplots combined. Or maybe the pipeline could just make separate files for summary lineplots and put those in results folder.

**Comment by jbloom** [comment]
I can work on this, but is it possible for you to find some workaround for short term as I have a lot of other stuff on my plate right now. But if this is high priority let me know and I will find time sooner.

**Comment by Bernadetadad** [comment]
@jbloom actually if you could do this when you have time that would be very useful.

**Comment by jbloom** [comment]
@Bernadetadad, this can now be done by adding the `no_heatmap` option as [here](https://github.com/dms-vep/dms-vep-pipeline-3/blob/main/test_example/data/summaries_config.yml#L28).

Note that this has to be done separately for each antibody set and phenotype for which you want to hide the heatmap.
