### ISSUE TITLE
Allowing strings for site numbering

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#29]
@jbloom Because H5 and H3 sequences are so different there are multiple sites in alignment where H5 has insertion or H3 is lacking the equivalent site. Previously in BA.1 we use something like 1a, 1b, 1c for insertions so I used the same for both H5 (sequential) and H3 (reference), but I'm now getting an error where script compares the length of protein to the length of sequential sequence because it is expecting numerical values.

I attach my `site_numbering_map` used for sequence conversion as well.

```
Cell In[10], line 22
     20 # read wildtype protein
     21 refprot = str(Bio.SeqIO.read(config["gene_sequence_protein"], "fasta").seq)
---> 22 assert len(refprot) >= site_numbering_map["sequential_site"].max()
     23 assert site_numbering_map["sequential_site"].min() >= 1
     25 # add reference site numbering and remove wildtype to wildtype mutations

TypeError: '>=' not supported between instances of 'int' and 'str'
``` 
[site_numbering_map.csv](https://github.com/dms-vep/dms-vep-pipeline-3/files/12264616/site_numbering_map.csv)

**Comment by jbloom** [comment]
@Bernadetadad, the `sequential_site` **must** be sequential 1, 2, 3, ... numbers that are the length of the parental protein used. I believe this restriction makes sense: that is the definition of sequential numbering. Your other numbering schemes (eg, reference numbering, H3 numbering, H5 numbering, etc) can then assign any numbers.

In the CSV attached, you have numbers like `16a` in your sequential numbering. Make your sequential numbering 1, 2, ..., `len(prot)`. Then define your H5 and H3 numbering as additional columns that map 1-to-1 to the sequential numbers. You can then also choose one of these to call `reference_site` as well.

Does this make sense? I think this is currently not a bug in the code but a bug in how you are trying to define the site numbering map.

**Comment by jbloom** [comment]
@Bernadetadad, can we close this issue as resolved by comment above, or did that not solve it?

**Comment by Bernadetadad** [comment]
closing
