### ISSUE TITLE
antibody_escape.smk bug or unclear issue with antibody selection input

### ISSUE THREAD

**Issue by caelanradford** [dms-vep/dms-vep-pipeline-3#32]
I converted my old antibody escape analysis to the new pipeline, but I am having an issue with Snakemake's determination of selection wildcards. For some reason it seems to be considering the first letter of each selection name to be the selection name, showing this error when I run Snakemake -n: 

InputFunctionException in rule fit_antibody_escape in file antibody_escape.smk, line 70:
Error:
  KeyError: 'A'
Wildcards:
  selection=A
Traceback:
  File "antibody_escape.smk", line 79, in <lambda>

I changed all the library labels to be "LibA" instead of just "A" and then it just changed the KeyError to "L". 

I am sure it is an issue with my inputs but I have not been able to figure out what it is.

**Comment by jbloom** [comment]
Can you point me to the repo that is giving you this error?

**Comment by jbloom** [comment]
@caelanradford, I think the issue is that under `avg_antibody_escape`, the `selections need to be a list. Right now you have just defined them as a str in YAML syntax.

In other words, you have:
```
avg_antibody_escape:
  antibody_name:
  selections:
    selection_1
    selection_2
```
It needs to be
```
avg_antibody_escape:
  antibody_name:
  selections:
    - selection_1
    - selection_2
```

In other words, in YAML, this is a nested dict:
```
key:
  key: value
```
this is a list:
```
mylist:
  - entry1
  - entry2
```
but this is just a string
```
not_a_list:
  entry1
  entry2
```

Does this fix the issue?

**Comment by caelanradford** [comment]
Yes, that was the error. Thanks for the help.
