### ISSUE TITLE
Fitting antibodies that don't fully neutralize

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#38]
@jbloom 2E7 mAb from Klein group does not fully neutralize virus and I think that's the reason why polyclonal fitting isn't working properly. I keep getting error `ValueError: wt_icXX=100000000.0 out of range check_wt_icXX=(1e-05, 100000.0)` that's because escape probabilities essentially flatten out and whatever curve it's trying to fit WT to looks to have very poor potency. The actual escape profiles look okay (attached) probably highest concentration should be removed but even if I do that it still can't fit properly. I also tried setting concentrations to mg/ml or g/ml and that does not solve the problem either.  Is there a way I can add a custom `polyclonal_params` that would set a different `check_wt_icXX` range? If I exclude the highest concentration I think one could fit a curve (not very precise) as the two lower point are not flat. The branch with this data is [here](https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/tree/sera_selections_250823) 
[Archive.zip](https://github.com/dms-vep/dms-vep-pipeline-3/files/12353074/Archive.zip)

**Comment by jbloom** [comment]
The issue may just be how you are setting the `XX` for the `icXX`? (I can't quite tell without seeing more details).

But basically, if an antibody never achieves more than say 80% neutralization, then you can't fit an IC90 as there is no concentration that gives 90% concentration. If you dropped the `XX` down to fitting say an IC50 for that antibody, then you could fit one.
