### ISSUE TITLE
Escape colour scale

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#40]
I noticed in my data for some RBD serum escape heatmaps  ([e.g ](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_RBD_DMS/notebooks/avg_escape_antibody_escape_sera_343C_mediumACE2.html)) it's quite hard to see the pale blue escape colors. I think the escape colour scale is not the best because it is essentially set by noisy sites that are either functionally very bad or have only one library measurement that gets filtered out from the display anyway. Would there perhaps be a better way for setting escape colour scale that would avoid using the outliers for setting min max values.

**Comment by jbloom** [comment]
Right now you can also set it manually, so maybe that would work?

But are you instead suggesting an option to set it to the max and min that are **not** filtered at the default settings for what is filtered? Right now it is set by max and min of all, including filtered.

Is that what you think would be best? If so, I can implement that.

**Comment by Bernadetadad** [comment]
yes, I think it would be bette to set max min based on what we are actually displaying and ignore what we filter out. For now I'll set them manually
