### ISSUE TITLE
de-clutter HTML docs

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline-3#41]
@Bernadetadad raised the concern that the HTML docs list too many things and so are hard to look at.

Perhaps these can be simplified.

**Comment by Bernadetadad** [comment]
Mostly I think some visual grouping would help.
Now you have just h2 headings I think it would help to add more subheadings to group data by type e.g.:

**<h2>Antibody/serum escape</h2>**
<h3>Analysis notebooks</h3>

- polyclonal model fits
- escape averages
- ...
<h3>Analysis plots</h3>

- antibody escape mutation effect plots 
- ...
<h3>Output datafiles</h3>

- antibody escape CSVs
- Probability (fraction) escape CSVs
- ...
