### ISSUE TITLE
Add `configure-dms-viz` to the pipeline 

### ISSUE THREAD

**Issue by WillHannon-MCB** [dms-vep/dms-vep-pipeline-3#61]
To get more people using [`dms-viz`](https://dms-viz.github.io/v0/) I think we should add a step to the pipeline to automatically generate the visualization specification.

**Comment by jbloom** [comment]
Just added you. Also, I think some thought should be given to how this will be added into pipeline. At what stage are planning to add it and what would be visualized? Would it try to read from the some configs given to the other plots already shown?

**Comment by WillHannon-MCB** [comment]
Agreed, I'll explore the pipeline and add my thoughts here.

**Comment by jbloom** [comment]
I'm closing this as I think it is better written as a custom rule, as is done in this repo: https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS

The reason I think better as custom rule is there is so much that can need customization.
