### ISSUE TITLE
add max_fixed to summary plots

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#69]
@jbloom can you add `max_fixed` value to summary config. It looks like currently you can only set `max_at_least` but not max. In reference to [SARS-CoV-2_XBB.1.5_spike_DMS/#34](https://github.com/dms-vep/SARS-CoV-2_XBB.1.5_spike_DMS/issues/34#issue-1908841846)

**Comment by jbloom** [comment]
@Bernadetadad, this is fixed in version 3.4.7. You can specify `fixed_max` or `fixed_min`.
