### ISSUE TITLE
Issue with displaying cutoff in 'analyze_func_scores'

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#87]
I don't know if this is a bug or expected behavior. The plot in the notebook `analyze_func_scores `showing the distribution of pre_counts has a red line showing where the threshold cutoff is applied for each sample (image attached). These values are set in `func_effects_config.yaml` with:
```
min_pre_selection_count: 20
min_pre_selection_frac: 0.00001

```
Thresholding the barcode counts should take the higher of these two numbers (I believe). It appears that regardless of what `min_pre_selection_frac` is set to, it always displays the red threshold line at the `min_pre_selection_count` instead. I was worried there was something wrong with the thresholding, but when I looked at the `func_scores` files themselves, it seems to properly be applying the min_pre_selection_frac cutoff. So I believe this is just a graphing issue.

<img width="471" alt="Screenshot 2023-11-07 at 7 52 21 AM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/89543163/3104ad35-b006-461b-b0fe-77d0508ce8ae">

**Comment by jbloom** [comment]
The bug was actually how it was being reported upstream of `analyze_func_scores`, not in the plotting itself. Will be fixed once I merge #88 and make version 3.5.4.
