### ISSUE TITLE
`multidms` fitting bug in func_effect_shifts.ipynb

### ISSUE THREAD

**Issue by jgallowa07** [dms-vep/dms-vep-pipeline-3#92]
While working on #86 , we encountered a bug in the lasso sweep code in the notebook 

```python
lasso_shifts = params["lasso_shifts"]
assert len(lasso_shifts) == len(set(lasso_shifts))
n_lasso = len(params["lasso_shifts"])
fig, ax = plt.subplots(n_lasso, 2, figsize=[6, n_lasso * 3])

model = multidms.Model(data)
mutations_df = []
for i, lasso_shift in enumerate(lasso_shifts):
    lasso_shift = float(lasso_shift)
    print(f"Fitting model for {lasso_shift=}")
    model.fit(lasso_shift=lasso_shift)
    mutations_df.append(
        model.get_mutations_df(phenotype_as_effect=True).assign(lasso_shift=lasso_shift)
    )
    model.plot_epistasis(ax=ax[i, 1], alpha=0.1, show=False, legend=not i)
    model.plot_pred_accuracy(ax=ax[i, 0], alpha=0.1, show=False, legend=False)
    ax[i, 1].set_title(f"Epistasis fit (lasso {lasso_shift})")
    ax[i, 0].set_title(f"Accuracy (lasso {lasso_shift})")

plt.show()
```

Here, the `model` object is only initialized once, meaning there is only a single set of parameters being re-fit for each of the lasso strengths in the loop. To fix this, we should simply need to move the model instantiation inside the loop.

**Comment by jbloom** [comment]
I merged the pull request that fixes this. But I would note, although I agree this new code makes sense, I'm not sure the prior code was truly a bug, was it? Starting each lasso from the results of the prior weight is also an arguably valid approach even if we think fitting each one independently is better, right? Or is there a reason why it was strictly speaking a bug before?

**Comment by jbloom** [comment]
Anyway, should have behavior you want now.
