### ISSUE TITLE
filtering low effect mutants in heatmaps for receptor binding and mAb escape

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline-3#96]
The pipeline currently colors boxes in the binding and mAb escape heatmaps dark gray if they have a low effect score but pass all the other filtering parameters (times seen, std, etc). Sites that have low effect scores but **don't** pass the other main filtering parameters get shown as not detected. After speaking with Jesse about this, we believe this is an issue since we already know those sites are bad for entry. So they should show up as dark gray in the heatmap (indicating low effect score) rather than not detected. The reason for this is because if a mutant is bad for entry, it is unlikely to show up at high frequency in the no antibody control or the antibody selections. It's not that we didn't ever measure that mutant, we know from functional selections it is bad for entry. 

I suggest we change the heatmap color scheme for mAbs or binding selections where we expect low entry score mutants to not be sampled very well. Any mutant that has a effect score less than some threshold should be colored dark grey (as long as it passes the cell entry times_seen filter), but is no longer filtered out based on the binding or escape times_seen filter.

In sum, mutants should be colored dark gray indicating a low effect score as long as those mutants pass the 'cell entry times seen' filtering parameter, but no other filtering should be applied to these sites (such as mAb times seen). We know the times_seen will be low because those mutants are bad for entry, and they should not be filtered out as missing data.

I am attaching a screenshot of an example. L111R has a cell entry score of -3.3 in CHO-EFNB2 cells. Currently the pipeline shows this mutant as 'not detected' because it doesn't pass the receptor times_seen filter. Shown here:
<img width="797" alt="Screenshot 2024-01-22 at 11 58 55 AM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/89543163/5f65768c-16fc-47f9-ad1e-f14d44f29517">

However, once removing the filtering parameters, the L111R mutant now shows up as a dark gray low effect mutation (as it should)
<img width="765" alt="Screenshot 2024-01-22 at 11 58 23 AM" src="https://github.com/dms-vep/dms-vep-pipeline-3/assets/89543163/90c0d4ba-8727-4a07-be3a-b629cca06476">

**Comment by jbloom** [comment]
This is fixed in #98 via upgrading to `polyclonal` update to 6.10
