### ISSUE TITLE
Add functional scores to multidms heatmaps

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#97]
@jbloom It would be nice to see functional effects of mutations when hovering over heatmaps showing multidms shifts. This would allow to immediately see if a mutation goes from very bad to slightly bad for entry or if it goes from being bad to being good for entry. Currently functional scores are not shown so it requires a lot of heatmap cross-referencing to figure out what's going on.

**Comment by jbloom** [comment]
#99 provides an alternative way to achieve the desired scientific goal here: we discussed and decided we just wanted simple differences rather than `multidms` shifts.
